### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by nysdan** [SBECK-github/Date-Manip#14] opened 2017-12-19 18:56 UTC
I'm trying to install a perl module that depends on Manip, but after installing Manip keeps giving an error like
Can't locate package Date::Manip::Obj for @Date::Manip::TZ::ISA at /export/home/....

MANIP VERSION: Date-Manip-6.60
Perl: v5.22.3

**Comment by SBECK-github** [comment] 2017-12-28 21:21
I'm sorry, but there simply isn't enough information to help you here.

Frankly, it looks to me like a problem with whatever other perl module you are installing.  You say you have installed Date::Manip.  Was it successful?  Can you use it (independent of this other module)?

If you can, then the problem is elsewhere.  Perhaps you've installed Date::Manip in a location where the other module isn't looking?

Good luck.

**Comment by SBECK-github** [comment] 2018-01-12 15:57
Closing this ticket.  Please reopen if the problem is confirmed to be due to something in Date::Manip

**Closed as completed by SBECK-github** 2018-01-12 15:57 UTC
